import axios from 'axios';
import * as cheerio from 'cheerio';
import { GoogleGenAI, Type, type Schema } from '@google/genai';
import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY as string });

// Target URLs for foundational endocrine systems
// Target URLs for a complete mapping of the human endocrine system
const TARGET_URLS = [
  // 🔴 Adrenal & Stress (HPA Axis)
  'https://en.wikipedia.org/wiki/Cortisol',
  'https://en.wikipedia.org/wiki/Adrenaline',
  'https://en.wikipedia.org/wiki/Aldosterone',

  // 🟠 Metabolic & Blood Sugar
  'https://en.wikipedia.org/wiki/Insulin',
  'https://en.wikipedia.org/wiki/Insulin_resistance',
  'https://en.wikipedia.org/wiki/Glucagon',

  // 🟡 Thyroid & Calcium System
  'https://en.wikipedia.org/wiki/Thyroid_hormone',
  'https://en.wikipedia.org/wiki/Thyroid-stimulating_hormone',
  'https://en.wikipedia.org/wiki/Parathyroid_hormone',

  // 🟢 Sex Hormones & Reproduction
  'https://en.wikipedia.org/wiki/Testosterone',
  'https://en.wikipedia.org/wiki/Estrogen',
  'https://en.wikipedia.org/wiki/Progesterone',

  // 🔵 Sleep, Appetite & Master Regulators
  'https://en.wikipedia.org/wiki/Melatonin',
  'https://en.wikipedia.org/wiki/Leptin',
  'https://en.wikipedia.org/wiki/Ghrelin',
  'https://en.wikipedia.org/wiki/Growth_hormone',
  
  // 🟣 Prohormones
  'https://en.wikipedia.org/wiki/Vitamin_D' 
];

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const responseSchema: Schema = {
  type: Type.ARRAY,
  description: "An array of strict biological cause-and-effect relationships.",
  items: {
    type: Type.OBJECT,
    properties: {
      sourceName: { type: Type.STRING },
      sourceType: { type: Type.STRING, description: "Must be exactly HORMONE_IMBALANCE or GLANDULAR_DYSFUNCTION." },
      targetName: { type: Type.STRING },
      targetType: { type: Type.STRING, description: "Must be exactly SYMPTOM, DISEASE, HORMONE_IMBALANCE, or DEFICIENCY." },
      relation: { type: Type.STRING },
      description: { type: Type.STRING }
    },
    required: ["sourceName", "sourceType", "targetName", "targetType", "relation", "description"]
  }
};

async function scrapeAndIngest() {
  console.log("🚀 Starting BioCascade Automated ETL Pipeline...");

  for (const url of TARGET_URLS) {
    try {
      console.log(`\n🌐 Scraping: ${url}`);
      
      // 1. Scrape the DOM
      const { data: html } = await axios.get(url);
      const $ = cheerio.load(html);
      
      // Extract text from paragraphs and lists, avoiding heavy tables/nav
      let scrapedText = '';
      $('#mw-content-text .mw-parser-output > p, #mw-content-text .mw-parser-output > ul li').each((_, el) => {
        scrapedText += $(el).text() + '\n';
      });

      // Truncate if necessary (keeping within safe token limits for API)
      const safeText = scrapedText.substring(0, 15000); 

      // 2. Process with Gemini
      console.log("🧠 Processing with Gemini 2.5 Flash...");
      const prompt = `Act as an expert endocrinologist. Analyze the following text and extract the pathological cascade of hormonal imbalances. 
      Focus on cause-and-effect biological relationships.
      Ensure the output strictly follows the JSON schema.
      
      Text to analyze:
      ${safeText}`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
           responseMimeType: "application/json",
           responseSchema: responseSchema,
        }
      });

      if (!response.text) throw new Error("Empty response from Gemini");
      
      const extractedData = JSON.parse(response.text);
      console.log(`✅ Extracted ${extractedData.length} edges. Saving to database...`);

      // 3. Ingest into PostgreSQL via Prisma
      for (const cascade of extractedData) {
        const sourceNode = await prisma.entity.upsert({
          where: { name: cascade.sourceName },
          update: {}, 
          create: {
            name: cascade.sourceName,
            type: cascade.sourceType,
            description: `Autogenerated from extraction.`
          }
        });

        const targetNode = await prisma.entity.upsert({
          where: { name: cascade.targetName },
          update: {}, 
          create: {
            name: cascade.targetName,
            type: cascade.targetType,
            description: cascade.description
          }
        });

        const existingEdge = await prisma.edge.findFirst({
          where: {
            sourceId: sourceNode.id,
            targetId: targetNode.id
          }
        });

        if (!existingEdge) {
          await prisma.edge.create({
            data: {
              sourceId: sourceNode.id,
              targetId: targetNode.id,
              relation: cascade.relation
            }
          });
        }
      }

      console.log(`💾 Successfully ingested data from ${url}`);

    } catch (error) {
      console.error(`❌ Failed processing ${url}:`, error);
    }

    // 4. Rate Limiting Protection (10 seconds)
    console.log("⏳ Applying 10,000ms delay to respect API limits...");
    await delay(10000);
  }

  console.log("\n🎉 ETL Pipeline Complete!");
}

scrapeAndIngest();